select*from customer;

--what is the revenue generated by male vs female customer?
select gender, sum(purchase_amount) as revenue
from customer
group by gender;

--which customer used discount still spend more than the avg purchase amount?
select customer_id, purchase_amount from customer
where discount_applied = 'Yes' and purchase_amount>=(select avg(purchase_amount) from customer);


--do subscribed customer spend more? compare avg spend and total revenue between subscriber and non subscriber
select subscription_status, count(customer_id) as total_customers, round(avg(purchase_amount),2) as avg_spend, round(sum(purchase_amount),2) as total_purchase
from customer
group by subscription_status;


--compare the avg purchase amount between std and express shipping
select shipping_type, avg(purchase_amount)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- top 5 products with highest percentage of purchase with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc limit 5;


--segment customer as new, returning, loyal based on their total number of previous purchases, and show count of each segment
--CTE question 
with customer_type as (
select customer_id, previous_purchases,
case 
     when previous_purchases=1 then 'New'
	 when previous_purchases between 2 and 10 then 'Returning'
	 else 'Loyal'
	 end as customer_segment
	 from customer
)
select customer_segment , count(*) as number_of_customers
from customer_type
group by customer_segment;

--what are the revenue contribution by each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;

--top 3 most purchased product in each category 
with item_count as 
(
   select category, item_purchased,
   count(customer_id) as total_orders,
   row_number() over( partition by category order by count(customer_id) desc) as item_rank 
   from customer
   group by category, item_purchased
)
   select item_rank, category, item_purchased, total_orders
   from item_count
   where item_rank<=3;


--are customers who are repeat buyers(more than 5 previous purchase) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_customers
from customer
where previous_purchases>=5 
group by subscription_status;

--which are the top 5 products with highest avg review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_product_review
from customer
group by item_purchased
order by avg(review_rating) desc limit 5 ;

--subscription status by gender (female-no subscription)
select gender, subscription_status, count(subscription_status)
from customer
group by gender,subscription_status


